In [1]:
import pandas as pd

In [28]:
features = pd.read_parquet('data/diabetes_features.parquet')
target = pd.read_parquet('data/diabetes_target.parquet')

# Columns and Data Types

In [3]:
print(features.info())

<class 'pandas.DataFrame'>
RangeIndex: 101766 entries, 0 to 101765
Data columns (total 49 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   encounter_id              101766 non-null  int64
 1   patient_nbr               101766 non-null  int64
 2   race                      101766 non-null  category
 3   gender                    101766 non-null  category
 4   age                       101766 non-null  category
 5   weight                    101766 non-null  category
 6   admission_type_id         101766 non-null  int64
 7   discharge_disposition_id  101766 non-null  int64
 8   admission_source_id       101766 non-null  int64
 9   time_in_hospital          101766 non-null  int64
 10  payer_code                101766 non-null  category
 11  medical_specialty         101766 non-null  category
 12  num_lab_procedures        101766 non-null  int64
 13  num_procedures            101766 non-null  int64
 14  num_medications           101766 non-null  int64
 15  number_outpatient         101766 non-null  int64
 16  number_emergency          101766 non-null  int64
 17  number_inpatient          101766 non-null  int64
 18  diag_1                    101766 non-null  category
 19  diag_2                    101766 non-null  category
 20  diag_3                    101766 non-null  category
 21  number_diagnoses          101766 non-null  int64
 22  max_glu_serum             101766 non-null  category
 23  A1Cresult                 101766 non-null  category
 24  metformin                 101766 non-null  category
 25  repaglinide               101766 non-null  category
 26  nateglinide               101766 non-null  category
 27  chlorpropamide            101766 non-null  category
 28  glimepiride               101766 non-null  category
 29  acetohexamide             101766 non-null  category
 30  glipizide                 101766 non-null  category
 31  glyburide                 101766 non-null  category
 32  tolbutamide               101766 non-null  category
 33  pioglitazone              101766 non-null  category
 34  rosiglitazone             101766 non-null  category
 35  acarbose                  101766 non-null  category
 36  miglitol                  101766 non-null  category
 37  troglitazone              101766 non-null  category
 38  tolazamide                101766 non-null  category
 39  examide                   101766 non-null  category
 40  citoglipton               101766 non-null  category
 41  insulin                   101766 non-null  category
 42  glyburide.metformin       101766 non-null  category
 43  glipizide.metformin       101766 non-null  category
 44  glimepiride.pioglitazone  101766 non-null  category
 45  metformin.rosiglitazone   101766 non-null  category
 46  metformin.pioglitazone    101766 non-null  category
 47  change                    101766 non-null  category
 48  diabetesMed               101766 non-null  category
dtypes: category(36), int64(13)
memory usage: 13.9 MB
None

In [4]:
for c in features.columns.values:
    print(c)

encounter_id
patient_nbr
race
gender
age
weight
admission_type_id
discharge_disposition_id
admission_source_id
time_in_hospital
payer_code
medical_specialty
num_lab_procedures
num_procedures
num_medications
number_outpatient
number_emergency
number_inpatient
diag_1
diag_2
diag_3
number_diagnoses
max_glu_serum
A1Cresult
metformin
repaglinide
nateglinide
chlorpropamide
glimepiride
acetohexamide
glipizide
glyburide
tolbutamide
pioglitazone
rosiglitazone
acarbose
miglitol
troglitazone
tolazamide
examide
citoglipton
insulin
glyburide.metformin
glipizide.metformin
glimepiride.pioglitazone
metformin.rosiglitazone
metformin.pioglitazone
change
diabetesMed

In [5]:
features.patient_nbr.value_counts()

patient_nbr
88785891     40
43140906     28
1660293      23
23199021     23
88227540     23
             ..
183087545     1
188574944     1
140199494     1
120975314     1
175429310     1
Name: count, Length: 71518, dtype: int64

In [6]:
# Exploring a single patient
features[features.patient_nbr == 88785891]

,encounter_id,patient_nbr,race,gender,age,weight,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,...,examide,citoglipton,insulin,glyburide.metformin,glipizide.metformin,glimepiride.pioglitazone,metformin.rosiglitazone,metformin.pioglitazone,change,diabetesMed
38307,119039172,88785891,Caucasian,Female,[20-30),?,1,1,7,1,...,No,No,Up,No,No,No,No,No,Ch,Yes
40252,125094312,88785891,Caucasian,Female,[20-30),?,1,1,7,1,...,No,No,Down,No,No,No,No,No,Ch,Yes
40661,126171582,88785891,Caucasian,Female,[20-30),?,1,1,7,5,...,No,No,Up,No,No,No,No,No,Ch,Yes
44515,137245596,88785891,Caucasian,Female,[20-30),?,3,1,7,2,...,No,No,Up,No,No,No,No,No,Ch,Yes
45147,139425576,88785891,Caucasian,Female,[20-30),?,1,1,7,2,...,No,No,Up,No,No,No,No,No,Ch,Yes
45986,141994242,88785891,Caucasian,Female,[20-30),?,2,1,7,4,...,No,No,Up,No,No,No,No,No,Ch,Yes
50167,150986298,88785891,Caucasian,Female,[20-30),?,2,1,7,1,...,No,No,Up,No,No,No,No,No,Ch,Yes
50393,151413846,88785891,Caucasian,Female,[20-30),?,1,1,7,4,...,No,No,Up,No,No,No,No,No,Ch,Yes
50773,152188656,88785891,Caucasian,Female,[20-30),?,2,7,7,1,...,No,No,Up,No,No,No,No,No,Ch,Yes
51519,153558456,88785891,Caucasian,Female,[20-30),?,2,1,7,1,...,No,No,Up,No,No,No,No,No,Ch,Yes
52057,154527444,88785891,Caucasian,Female,[20-30),?,2,1,7,1,...,No,No,Up,No,No,No,No,No,Ch,Yes
53771,157363182,88785891,Caucasian,Female,[20-30),?,2,1,7,2,...,No,No,Down,No,No,No,No,No,Ch,Yes
54497,158500410,88785891,Caucasian,Female,[20-30),?,2,1,7,3,...,No,No,Down,No,No,No,No,No,Ch,Yes
60263,168920160,88785891,Caucasian,Female,[20-30),?,1,1,7,8,...,No,No,Up,No,No,No,No,No,Ch,Yes
62759,174689286,88785891,Caucasian,Female,[20-30),?,1,1,7,3,...,No,No,Up,No,No,No,No,No,Ch,Yes
63165,175632402,88785891,Caucasian,Female,[20-30),?,2,1,7,4,...,No,No,Down,No,No,No,No,No,Ch,Yes
65667,183194856,88785891,Caucasian,Female,[20-30),?,1,1,7,2,...,No,No,Up,No,No,No,No,No,Ch,Yes
67968,191345028,88785891,Caucasian,Female,[20-30),?,3,1,7,5,...,No,No,Down,No,No,No,No,No,Ch,Yes
71029,205106328,88785891,Caucasian,Female,[20-30),?,2,1,7,1,...,No,No,Up,No,No,No,No,No,Ch,Yes
72068,210079272,88785891,Caucasian,Female,[20-30),?,1,7,7,2,...,No,No,Down,No,No,No,No,No,Ch,Yes
74405,221588430,88785891,Caucasian,Female,[20-30),?,2,1,7,1,...,No,No,Up,No,No,No,No,No,Ch,Yes
74876,223647786,88785891,Caucasian,Female,[20-30),?,2,1,7,2,...,No,No,Down,No,No,No,No,No,Ch,Yes
75267,225428574,88785891,Caucasian,Female,[20-30),?,2,1,7,2,...,No,No,Down,No,No,No,No,No,Ch,Yes
76525,230986482,88785891,Caucasian,Female,[20-30),?,2,1,7,7,...,No,No,Up,No,No,No,No,No,Ch,Yes
76907,232655340,88785891,Caucasian,Female,[20-30),?,2,1,7,4,...,No,No,Down,No,No,No,No,No,Ch,Yes
78355,239153370,88785891,Caucasian,Female,[20-30),?,1,1,7,7,...,No,No,Up,No,No,No,No,No,Ch,Yes
78882,241426656,88785891,Caucasian,Female,[20-30),?,1,1,7,3,...,No,No,Up,No,No,No,No,No,Ch,Yes
79202,242844252,88785891,Caucasian,Female,[20-30),?,2,1,7,1,...,No,No,Up,No,No,No,No,No,Ch,Yes
79467,243967338,88785891,Caucasian,Female,[20-30),?,2,1,7,1,...,No,No,Up,No,No,No,No,No,Ch,Yes
82693,257757342,88785891,Caucasian,Female,[20-30),?,2,7,7,2,...,No,No,Down,No,No,No,No,No,Ch,Yes
87063,277490424,88785891,Caucasian,Female,[20-30),?,1,1,7,7,...,No,No,Down,No,No,No,No,No,Ch,Yes
87854,281267754,88785891,Caucasian,Female,[20-30),?,1,1,7,7,...,No,No,Up,No,No,No,No,No,Ch,Yes
88392,284109186,88785891,Caucasian,Female,[20-30),?,1,1,7,3,...,No,No,Up,No,No,No,No,No,Ch,Yes
89964,291808098,88785891,Caucasian,Female,[20-30),?,1,5,7,6,...,No,No,Down,No,No,No,No,No,Ch,Yes
90913,302508452,88785891,Caucasian,Female,[20-30),?,2,1,7,5,...,No,No,Up,No,No,No,No,No,Ch,Yes
91444,309563132,88785891,Caucasian,Female,[20-30),?,1,1,7,3,...,No,No,Up,No,No,No,No,No,Ch,Yes
97433,388509176,88785891,Caucasian,Female,[20-30),?,2,1,7,5,...,No,No,Down,No,No,No,No,No,Ch,Yes
97732,392073212,88785891,Caucasian,Female,[20-30),?,1,1,7,3,...,No,No,Up,No,No,No,No,No,Ch,Yes
99950,419611106,88785891,Caucasian,Female,[20-30),?,2,1,7,2,...,No,No,Up,No,No,No,No,No,Ch,Yes
101385,438529178,88785891,Caucasian,Female,[20-30),?,3,7,4,3,...,No,No,No,No,No,No,No,No,No,No

# Missing Data

#### Key Findings

- Weight is missing for an entire patient, except for 36 patients captured below
- Missing values are encoded in some columns using "?" and None

In [7]:
# Diagnosing if weight is always missing for a patient
weight_diagnostic = features.loc[:, ['patient_nbr', 'weight']]

weight_diagnostic['missing_weight'] = weight_diagnostic['weight'].apply(lambda x: 1 if x == "?" else 0)

# Group and aggregate
grouped = weight_diagnostic.groupby('patient_nbr').agg({
    'missing_weight': 'sum',  # count of missing weights
    'weight': 'count'          # total records for that patient
})

# Patients where missing_weight == total records are always missing
grouped['always_missing'] = grouped['missing_weight'] == grouped['weight']

grouped[(grouped["missing_weight"] != grouped['weight']) & (grouped["missing_weight"] > 0)]

             missing_weight  weight  always_missing
patient_nbr
1743804                   1       2           False
3515238                   1       2           False
4019499                   1       2           False
4790016                   1       8           False
6316542                   1       2           False
7994817                   1       2           False
21684645                  1       2           False
30775878                  1       2           False
35879364                  1       2           False
42846687                  1       2           False
43913259                  1       2           False
54253962                  1       3           False
55030950                  1       2           False
56356434                  1       2           False
61591977                  1       2           False
67629474                  1       2           False
70778790                  1       2           False
73498194                  1       2           False
76976226                  1       2           False
77741667                  1       2           False
81622962                  1       3           False
82938132                  1       2           False
86704641                  1       5           False
89750664                  1       2           False
91223523                  1       3           False
99801477                  1       3           False
100140957                 1       2           False
100178811                 1       3           False
101011626                 1       2           False
103333095                 1       2           False
104180580                 1       2           False
110735343                 1       3           False
110907864                 1       6           False
110949741                 1       2           False
112596327                 1       4           False
114725556                 1       2           False

In [8]:
# Inspecting one patient that has mixed missing data
features[features.patient_nbr == 4790016]

,encounter_id,patient_nbr,race,gender,age,weight,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,...,examide,citoglipton,insulin,glyburide.metformin,glipizide.metformin,glimepiride.pioglitazone,metformin.rosiglitazone,metformin.pioglitazone,change,diabetesMed
18056,65754690,4790016,Caucasian,Female,[20-30),[50-75),2,1,1,1,...,No,No,No,No,No,No,No,No,No,No
23306,79654248,4790016,Caucasian,Female,[20-30),[50-75),1,1,7,7,...,No,No,Up,No,No,No,No,No,Ch,Yes
24608,83243016,4790016,Caucasian,Female,[20-30),?,2,18,4,1,...,No,No,No,No,No,No,No,No,No,No
28426,93131496,4790016,Caucasian,Female,[20-30),[75-100),1,5,6,3,...,No,No,Up,No,No,No,No,No,Ch,Yes
32564,103670874,4790016,Caucasian,Female,[20-30),[50-75),1,1,7,1,...,No,No,Steady,No,No,No,No,No,No,Yes
49008,148883136,4790016,Caucasian,Female,[20-30),[50-75),1,1,7,7,...,No,No,No,No,No,No,No,No,No,No
61923,172669098,4790016,Caucasian,Female,[20-30),[50-75),1,1,7,3,...,No,No,Up,No,No,No,No,No,Ch,Yes
74378,221409540,4790016,Caucasian,Female,[20-30),[50-75),1,1,7,1,...,No,No,Up,No,No,No,No,No,Ch,Yes

### Diving into the use of Identifiers ("?", None) for missing data

In [9]:
qmark_missing = (features == "?").sum()
print(qmark_missing[qmark_missing > 0])

race                  2273
weight               98569
payer_code           40256
medical_specialty    49949
diag_1                  21
diag_2                 358
diag_3                1423
dtype: int64

In [10]:
none_missing = (features == "None").sum()
print(none_missing[none_missing > 0])

max_glu_serum    96420
A1Cresult        84748
dtype: int64

#### Correlation of Missing Values

In [29]:
((features == "?") | (features == "None")).astype(int).corr().round(4)

,encounter_id,patient_nbr,race,gender,age,weight,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,...,examide,citoglipton,insulin,glyburide.metformin,glipizide.metformin,glimepiride.pioglitazone,metformin.rosiglitazone,metformin.pioglitazone,change,diabetesMed
encounter_id,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
patient_nbr,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
race,NaN,NaN,1.0000,NaN,NaN,-0.0254,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
gender,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
age,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
weight,NaN,NaN,-0.0254,NaN,NaN,1.0000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
admission_type_id,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
discharge_disposition_id,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
admission_source_id,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
time_in_hospital,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
payer_code,NaN,NaN,-0.0483,NaN,NaN,0.0441,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
medical_specialty,NaN,NaN,0.0090,NaN,NaN,0.0020,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
num_lab_procedures,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
num_procedures,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
num_medications,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
number_outpatient,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
number_emergency,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
number_inpatient,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
diag_1,NaN,NaN,0.0071,NaN,NaN,0.0026,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
diag_2,NaN,NaN,0.0157,NaN,NaN,-0.0007,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
diag_3,NaN,NaN,0.0239,NaN,NaN,0.0099,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
number_diagnoses,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max_glu_serum,NaN,NaN,0.0189,NaN,NaN,-0.0424,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
A1Cresult,NaN,NaN,-0.0075,NaN,NaN,-0.0285,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
metformin,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
repaglinide,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
nateglinide,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
chlorpropamide,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
glimepiride,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
acetohexamide,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
glipizide,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
glyburide,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
tolbutamide,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
pioglitazone,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
rosiglitazone,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
acarbose,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
miglitol,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
troglitazone,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
tolazamide,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
examide,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
citoglipton,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
insulin,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
glyburide.metformin,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
glipizide.metformin,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
glimepiride.pioglitazone,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
metformin.rosiglitazone,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
metformin.pioglitazone,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
change,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
diabetesMed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

#### Exploring Patterns in Missing Data

Missing data in the following columns depends on admission type and admission source:

- max_glu_serum
- A1Cresult
- weight
- payer_code
- medical_specialty

This pattern suggests data is MAR with dependency on the admission source and type. A Preliminary approach is to fit the model after subsetting by admission type and source, or picking a model (i.e. tree-based) that will automatically subset the data

In [ ]:
# Admission Type
for f in ['max_glu_serum', 'A1Cresult', 'weight', 'payer_code', 'medical_specialty']:
    ct = pd.crosstab(features['admission_type_id'], features[f])
    print(ct.apply(lambda x: x / sum(x), axis = 1))

max_glu_serum          >200      >300      None      Norm
admission_type_id
1                  0.002704  0.006186  0.984182  0.006927
2                  0.002652  0.002110  0.988366  0.006872
3                  0.000053  0.000318  0.998781  0.000848
4                  0.000000  0.000000  1.000000  0.000000
5                  0.173250  0.116405  0.422571  0.287774
6                  0.086940  0.061992  0.718201  0.132867
7                  0.000000  0.000000  1.000000  0.000000
8                  0.000000  0.000000  1.000000  0.000000
A1Cresult                >7        >8      None      Norm
admission_type_id
1                  0.040415  0.093073  0.807964  0.058548
2                  0.044048  0.077597  0.827219  0.051136
3                  0.025704  0.045736  0.897557  0.031003
4                  0.200000  0.000000  0.800000  0.000000
5                  0.026332  0.047022  0.907001  0.019645
6                  0.035154  0.120960  0.808354  0.035532
7                  0.000000  0.000000  0.809524  0.190476
8                  0.053125  0.090625  0.815625  0.040625
weight                 >200         ?    [0-25)  [100-125)  [125-150)  \
admission_type_id
1                  0.000037  0.971976  0.000093   0.005186   0.001315
2                  0.000000  0.976786  0.000000   0.005519   0.001299
3                  0.000000  0.960093  0.000477   0.009380   0.002014
4                  0.000000  0.800000  0.000000   0.000000   0.000000
5                  0.000000  0.999373  0.000000   0.000209   0.000000
6                  0.000189  0.906067  0.006426   0.012285   0.002268
7                  0.000000  1.000000  0.000000   0.000000   0.000000
8                  0.000000  1.000000  0.000000   0.000000   0.000000

weight             [150-175)  [175-200)   [25-50)   [50-75)  [75-100)
admission_type_id
1                   0.000352   0.000130  0.000945  0.009002  0.010965
2                   0.000162   0.000162  0.000758  0.005844  0.009470
3                   0.000530   0.000000  0.000477  0.008374  0.018655
4                   0.000000   0.000000  0.000000  0.100000  0.100000
5                   0.000000   0.000000  0.000000  0.000209  0.000209
6                   0.000567   0.000189  0.004347  0.027027  0.040635
7                   0.000000   0.000000  0.000000  0.000000  0.000000
8                   0.000000   0.000000  0.000000  0.000000  0.000000
payer_code                ?        BC        CH        CM        CP        DM  \
admission_type_id
1                  0.366716  0.042897  0.001593  0.023967  0.028079  0.007390
2                  0.374892  0.051136  0.000649  0.012662  0.020779  0.002597
3                  0.333775  0.066776  0.002279  0.020722  0.030791  0.003498
4                  0.500000  0.000000  0.000000  0.100000  0.200000  0.000000
5                  0.338349  0.028004  0.001045  0.003553  0.008568  0.007524
6                  0.999244  0.000000  0.000000  0.000000  0.000189  0.000000
7                  0.000000  0.000000  0.000000  0.000000  0.380952  0.000000
8                  1.000000  0.000000  0.000000  0.000000  0.000000  0.000000

payer_code               HM        MC        MD        OT        PO        SI  \
admission_type_id
1                  0.073199  0.344712  0.035525  0.001148  0.006594  0.000074
2                  0.059470  0.292695  0.035390  0.000649  0.002056  0.000541
3                  0.037098  0.333987  0.043087  0.001113  0.010440  0.000000
4                  0.000000  0.100000  0.000000  0.000000  0.000000  0.000000
5                  0.108464  0.440961  0.030303  0.000000  0.000000  0.008568
6                  0.000000  0.000000  0.000189  0.000000  0.000000  0.000000
7                  0.190476  0.285714  0.047619  0.000000  0.047619  0.000000
8                  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000

payer_code               SP        UN        WC        OG        MP        FR
admission_type_id
1                  0.037637  0.019115  0.000889  0.009465  0.001000  0.000000
2                  0.075487  0.051786  0.001245  0.016937  0.000974  0.000054
3                  0.080343  0.021888  0.003074  0.010917  0.000212  0.000000
4                  0.000000  0.100000  0.000000  0.000000  0.000000  0.000000
5                  0.013166  0.009195  0.001254  0.000418  0.000627  0.000000
6                  0.000189  0.000189  0.000000  0.000000  0.000000  0.000000
7                  0.000000  0.000000  0.000000  0.047619  0.000000  0.000000
8                  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000
medical_specialty         ?  AllergyandImmunology  Anesthesiology  \
admission_type_id
1                  0.615762              0.000000        0.000056
2                  0.296807              0.000054        0.000162
3                  0.358578              0.000000        0.000318
4                  0.800000              0.000000        0.000000
5                  0.632811              0.000000        0.000000
6                  0.257040              0.001134        0.000000
7                  1.000000              0.000000        0.000000
8                  0.112500              0.000000        0.000000

medical_specialty  Anesthesiology-Pediatric  Cardiology  Dentistry  \
admission_type_id
1                                  0.000222    0.030172   0.000019
2                                  0.000216    0.055032   0.000108
3                                  0.000106    0.091685   0.000000
4                                  0.000000    0.000000   0.000000
5                                  0.000000    0.032602   0.000000
6                                  0.000189    0.149877   0.000189
7                                  0.000000    0.000000   0.000000
8                                  0.000000    0.084375   0.000000

medical_specialty  Emergency/Trauma  Endocrinology  Family/GeneralPractice  \
admission_type_id
1                          0.045416       0.001334                0.064549
2                          0.227219       0.001894                0.075866
3                          0.047167       0.000212                0.056336
4                          0.000000       0.000000                0.100000
5                          0.000209       0.000000                0.160920
6                          0.004347       0.001701                0.134001
7                          0.000000       0.000000                0.000000
8                          0.000000       0.000000                0.031250

medical_specialty  Gastroenterology  ...  Radiologist    Speech  \
admission_type_id                    ...
1                          0.003093  ...     0.002167  0.000000
2                          0.013095  ...     0.013907  0.000000
3                          0.005300  ...     0.040596  0.000000
4                          0.000000  ...     0.000000  0.000000
5                          0.004807  ...     0.000000  0.000000
6                          0.006048  ...     0.000000  0.000189
7                          0.000000  ...     0.000000  0.000000
8                          0.000000  ...     0.000000  0.000000

medical_specialty  SportsMedicine  SurgicalSpecialty  Cardiology-Pediatric  \
admission_type_id
1                        0.000000           0.000056              0.000000
2                        0.000054           0.000541              0.000379
3                        0.000000           0.001060              0.000000
4                        0.000000           0.000000              0.000000
5                        0.000000           0.000000              0.000000
6                        0.000000           0.000000              0.000000
7                        0.000000           0.000000              0.000000
8                        0.000000           0.000000              0.000000

medical_specialty  Perinatology  Neurophysiology   DCPTEAM  \
admission_type_id
1                      0.000000         0.000000  0.000037
2                      0.000000         0.000000  0.000054
3                      0.000053         0.000053  0.000159
4                      0.000000         0.000000  0.000000
5                      0.000000         0.000000  0.000000
6                      0.000000         0.000000  0.000000
7                      0.000000         0.000000  0.000000
8                      0.000000         0.000000  0.000000

medical_specialty  Endocrinology-Metabolism  Resident
admission_type_id
1                                  0.000130  0.000037
2                                  0.000000  0.000000
3                                  0.000053  0.000000
4                                  0.000000  0.000000
5                                  0.000000  0.000000
6                                  0.000000  0.000000
7                                  0.000000  0.000000
8                                  0.000000  0.000000

[8 rows x 73 columns]

In [47]:
# Admission Source
for f in ['max_glu_serum', 'A1Cresult', 'weight', 'payer_code', 'medical_specialty']:
    ct = pd.crosstab(features['admission_source_id'], features[f])
    print(ct.apply(lambda x: x / sum(x), axis = 1))

max_glu_serum            >200      >300      None      Norm
admission_source_id
1                    0.001657  0.001421  0.992559  0.004363
2                    0.006341  0.001812  0.980978  0.010870
3                    0.000000  0.000000  1.000000  0.000000
4                    0.000000  0.000314  0.999686  0.000000
5                    0.000000  0.000000  1.000000  0.000000
6                    0.000000  0.000000  1.000000  0.000000
7                    0.005079  0.008418  0.978833  0.007670
8                    0.000000  0.000000  1.000000  0.000000
9                    0.000000  0.000000  1.000000  0.000000
10                   0.000000  0.000000  1.000000  0.000000
11                   0.000000  0.000000  1.000000  0.000000
13                   0.000000  0.000000  1.000000  0.000000
14                   0.000000  0.000000  1.000000  0.000000
17                   0.167674  0.108391  0.426781  0.297154
20                   0.000000  0.000000  1.000000  0.000000
22                   0.000000  0.000000  1.000000  0.000000
25                   0.000000  0.000000  1.000000  0.000000
A1Cresult                  >7        >8      None      Norm
admission_source_id
1                    0.032843  0.062980  0.865652  0.038525
2                    0.011775  0.026268  0.935688  0.026268
3                    0.037433  0.096257  0.823529  0.042781
4                    0.030750  0.067148  0.862567  0.039536
5                    0.021053  0.022222  0.921637  0.035088
6                    0.050353  0.121466  0.768110  0.060071
7                    0.043083  0.094966  0.802449  0.059502
8                    0.000000  0.125000  0.750000  0.125000
9                    0.056000  0.112000  0.816000  0.016000
10                   0.125000  0.375000  0.125000  0.375000
11                   0.000000  0.000000  1.000000  0.000000
13                   0.000000  0.000000  1.000000  0.000000
14                   0.500000  0.000000  0.500000  0.000000
17                   0.014305  0.045569  0.927592  0.012535
20                   0.049689  0.068323  0.844720  0.037267
22                   0.000000  0.000000  0.833333  0.166667
25                   0.000000  0.000000  0.500000  0.500000
weight                   >200         ?    [0-25)  [100-125)  [125-150)  \
admission_source_id
1                    0.000000  0.965297  0.000304   0.008490   0.001793
2                    0.000000  1.000000  0.000000   0.000000   0.000000
3                    0.000000  1.000000  0.000000   0.000000   0.000000
4                    0.000000  0.956385  0.000941   0.009099   0.002824
5                    0.000000  0.792982  0.002339   0.014035   0.004678
6                    0.000000  0.942138  0.000000   0.002650   0.000883
7                    0.000035  0.977354  0.000070   0.004661   0.001148
8                    0.000000  1.000000  0.000000   0.000000   0.000000
9                    0.000000  1.000000  0.000000   0.000000   0.000000
10                   0.000000  1.000000  0.000000   0.000000   0.000000
11                   0.000000  1.000000  0.000000   0.000000   0.000000
13                   0.000000  1.000000  0.000000   0.000000   0.000000
14                   0.000000  1.000000  0.000000   0.000000   0.000000
17                   0.000147  0.937767  0.004424   0.008701   0.001622
20                   0.000000  1.000000  0.000000   0.000000   0.000000
22                   0.000000  1.000000  0.000000   0.000000   0.000000
25                   0.000000  1.000000  0.000000   0.000000   0.000000

weight               [150-175)  [175-200)   [25-50)   [50-75)  [75-100)
admission_source_id
1                     0.000406   0.000135  0.000609  0.007543  0.015424
2                     0.000000   0.000000  0.000000  0.000000  0.000000
3                     0.000000   0.000000  0.000000  0.000000  0.000000
4                     0.000000   0.000000  0.001255  0.010355  0.019140
5                     0.002339   0.000000  0.010526  0.099415  0.073684
6                     0.000000   0.000000  0.001767  0.028269  0.024293
7                     0.000313   0.000122  0.000783  0.006418  0.009097
8                     0.000000   0.000000  0.000000  0.000000  0.000000
9                     0.000000   0.000000  0.000000  0.000000  0.000000
10                    0.000000   0.000000  0.000000  0.000000  0.000000
11                    0.000000   0.000000  0.000000  0.000000  0.000000
13                    0.000000   0.000000  0.000000  0.000000  0.000000
14                    0.000000   0.000000  0.000000  0.000000  0.000000
17                    0.000442   0.000000  0.002507  0.018139  0.026250
20                    0.000000   0.000000  0.000000  0.000000  0.000000
22                    0.000000   0.000000  0.000000  0.000000  0.000000
25                    0.000000   0.000000  0.000000  0.000000  0.000000
payer_code                  ?        BC        CH        CM        CP  \
admission_source_id
1                    0.365263  0.061559  0.001928  0.014071  0.026788
2                    0.942935  0.002717  0.000000  0.001812  0.000906
3                    0.834225  0.005348  0.000000  0.000000  0.016043
4                    0.636021  0.025102  0.000314  0.018513  0.017885
5                    0.397661  0.005848  0.000000  0.019883  0.007018
6                    0.058304  0.051678  0.000000  0.005742  0.012809
7                    0.357237  0.044231  0.001478  0.024594  0.028003
8                    0.500000  0.000000  0.000000  0.000000  0.000000
9                    0.008000  0.096000  0.000000  0.000000  0.040000
10                   0.250000  0.125000  0.000000  0.000000  0.000000
11                   0.000000  0.000000  0.000000  0.500000  0.000000
13                   0.000000  0.000000  0.000000  1.000000  0.000000
14                   0.000000  0.000000  0.000000  0.500000  0.000000
17                   0.744580  0.010765  0.000442  0.001622  0.004277
20                   1.000000  0.000000  0.000000  0.000000  0.000000
22                   0.083333  0.000000  0.000000  0.083333  0.083333
25                   0.000000  0.000000  0.000000  0.500000  0.000000

payer_code                 DM        HM        MC        MD        OT  \
admission_source_id
1                    0.004262  0.065720  0.328666  0.034466  0.000981
2                    0.000000  0.001812  0.035326  0.000906  0.000000
3                    0.000000  0.000000  0.096257  0.005348  0.000000
4                    0.002196  0.030436  0.192344  0.023219  0.000941
5                    0.002339  0.014035  0.479532  0.038596  0.000000
6                    0.000442  0.134276  0.465548  0.070230  0.000000
7                    0.006888  0.063137  0.336279  0.037517  0.001096
8                    0.000000  0.187500  0.250000  0.062500  0.000000
9                    0.000000  0.136000  0.384000  0.088000  0.000000
10                   0.000000  0.000000  0.000000  0.250000  0.000000
11                   0.000000  0.000000  0.000000  0.500000  0.000000
13                   0.000000  0.000000  0.000000  0.000000  0.000000
14                   0.000000  0.000000  0.000000  0.000000  0.000000
17                   0.002507  0.039227  0.176228  0.010618  0.000000
20                   0.000000  0.000000  0.000000  0.000000  0.000000
22                   0.000000  0.000000  0.500000  0.083333  0.000000
25                   0.000000  0.000000  0.500000  0.000000  0.000000

payer_code                 PO        SI        SP        UN        WC  \
admission_source_id
1                    0.007509  0.001049  0.049789  0.028378  0.002537
2                    0.000000  0.000000  0.008152  0.003623  0.000000
3                    0.000000  0.000000  0.005348  0.037433  0.000000
4                    0.003138  0.000000  0.015375  0.029181  0.000628
5                    0.000000  0.000000  0.014035  0.017544  0.001170
6                    0.001325  0.000000  0.015459  0.181537  0.001325
7                    0.006192  0.000122  0.059137  0.017845  0.000922
8                    0.000000  0.000000  0.000000  0.000000  0.000000
9                    0.000000  0.000000  0.032000  0.208000  0.000000
10                   0.000000  0.000000  0.000000  0.250000  0.000000
11                   0.000000  0.000000  0.000000  0.000000  0.000000
13                   0.000000  0.000000  0.000000  0.000000  0.000000
14                   0.000000  0.000000  0.000000  0.500000  0.000000
17                   0.000000  0.002507  0.003687  0.003392  0.000147
20                   0.000000  0.000000  0.000000  0.000000  0.000000
22                   0.083333  0.000000  0.000000  0.083333  0.000000
25                   0.000000  0.000000  0.000000  0.000000  0.000000

payer_code                 OG        MP        FR
admission_source_id
1                    0.006325  0.000676  0.000034
2                    0.001812  0.000000  0.000000
3                    0.000000  0.000000  0.000000
4                    0.004079  0.000628  0.000000
5                    0.002339  0.000000  0.000000
6                    0.001325  0.000000  0.000000
7                    0.014349  0.000974  0.000000
8                    0.000000  0.000000  0.000000
9                    0.008000  0.000000  0.000000
10                   0.000000  0.125000  0.000000
11                   0.000000  0.000000  0.000000
13                   0.000000  0.000000  0.000000
14                   0.000000  0.000000  0.000000
17                   0.000000  0.000000  0.000000
20                   0.000000  0.000000  0.000000
22                   0.000000  0.000000  0.000000
25                   0.000000  0.000000  0.000000
medical_specialty           ?  AllergyandImmunology  Anesthesiology  \
admission_source_id
1                    0.394081              0.000034        0.000304
2                    0.830616              0.000000        0.000000
3                    0.759358              0.000000        0.000000
4                    0.529024              0.000000        0.000314
5                    0.408187              0.000000        0.000000
6                    0.188604              0.000000        0.000000
7                    0.558128              0.000104        0.000035
8                    0.250000              0.000000        0.000000
9                    0.048000              0.000000        0.000000
10                   0.750000              0.000000        0.000000
11                   1.000000              0.000000        0.000000
13                   0.000000              0.000000        0.000000
14                   0.500000              0.000000        0.000000
17                   0.368235              0.000000        0.000000
20                   1.000000              0.000000        0.000000
22                   0.750000              0.000000        0.000000
25                   1.000000              0.000000        0.000000

medical_specialty    Anesthesiology-Pediatric  Cardiology  Dentistry  \
admission_source_id
1                                    0.000169    0.083477   0.000068
2                                    0.000000    0.006341   0.000000
3                                    0.000000    0.000000   0.000000
4                                    0.000941    0.112331   0.000000
5                                    0.000000    0.031579   0.000000
6                                    0.000000    0.028710   0.000000
7                                    0.000191    0.027412   0.000035
8                                    0.000000    0.000000   0.000000
9                                    0.000000    0.008000   0.000000
10                                   0.000000    0.125000   0.000000
11                                   0.000000    0.000000   0.000000
13                                   0.000000    0.000000   0.000000
14                                   0.000000    0.000000   0.000000
17                                   0.000000    0.125203   0.000000
20                                   0.000000    0.000000   0.000000
22                                   0.000000    0.000000   0.000000
25                                   0.000000    0.000000   0.000000

medical_specialty    Emergency/Trauma  Endocrinology  Family/GeneralPractice  \
admission_source_id
1                            0.012582       0.001319                0.061086
2                            0.006341       0.000000                0.030797
3                            0.000000       0.000000                0.000000
4                            0.001883       0.000628                0.028553
5                            0.049123       0.000000                0.084211
6                            0.015901       0.004859                0.163428
7                            0.123404       0.001165                0.060615
8                            0.250000       0.000000                0.062500
9                            0.008000       0.008000                0.192000
10                           0.000000       0.000000                0.000000
11                           0.000000       0.000000                0.000000
13                           0.000000       0.000000                0.000000
14                           0.000000       0.000000                0.000000
17                           0.000295       0.000000                0.229612
20                           0.000000       0.000000                0.000000
22                           0.000000       0.000000                0.000000
25                           0.000000       0.000000                0.000000

medical_specialty    Gastroenterology  ...  Radiologist    Speech  \
admission_source_id                    ...
1                            0.011128  ...     0.031558  0.000000
2                            0.007246  ...     0.000000  0.000000
3                            0.000000  ...     0.000000  0.000000
4                            0.002196  ...     0.032633  0.000000
5                            0.003509  ...     0.002339  0.000000
6                            0.001325  ...     0.001767  0.000000
7                            0.003044  ...     0.001687  0.000017
8                            0.000000  ...     0.000000  0.000000
9                            0.016000  ...     0.000000  0.000000
10                           0.000000  ...     0.000000  0.000000
11                           0.000000  ...     0.000000  0.000000
13                           0.000000  ...     0.000000  0.000000
14                           0.000000  ...     0.000000  0.000000
17                           0.005456  ...     0.000000  0.000000
20                           0.000000  ...     0.000000  0.000000
22                           0.000000  ...     0.000000  0.000000
25                           0.000000  ...     0.000000  0.000000

medical_specialty    SportsMedicine  SurgicalSpecialty  Cardiology-Pediatric  \
admission_source_id
1                          0.000034           0.001049              0.000169
2                          0.000000           0.000000              0.000000
3                          0.000000           0.000000              0.000000
4                          0.000000           0.000000              0.000314
5                          0.000000           0.000000              0.000000
6                          0.000000           0.000442              0.000000
7                          0.000000           0.000017              0.000017
8                          0.000000           0.000000              0.000000
9                          0.000000           0.000000              0.000000
10                         0.000000           0.000000              0.000000
11                         0.000000           0.000000              0.000000
13                         0.000000           0.000000              0.000000
14                         0.000000           0.000000              0.000000
17                         0.000000           0.000000              0.000000
20                         0.000000           0.000000              0.000000
22                         0.000000           0.000000              0.000000
25                         0.000000           0.000000              0.000000

medical_specialty    Perinatology  Neurophysiology   DCPTEAM  \
admission_source_id
1                        0.000034         0.000034  0.000135
2                        0.000000         0.000000  0.000000
3                        0.000000         0.000000  0.000000
4                        0.000000         0.000000  0.000000
5                        0.000000         0.000000  0.000000
6                        0.000000         0.000000  0.000000
7                        0.000000         0.000000  0.000035
8                        0.000000         0.000000  0.000000
9                        0.000000         0.000000  0.000000
10                       0.000000         0.000000  0.000000
11                       0.000000         0.000000  0.000000
13                       0.000000         0.000000  0.000000
14                       0.000000         0.000000  0.000000
17                       0.000000         0.000000  0.000000
20                       0.000000         0.000000  0.000000
22                       0.000000         0.000000  0.000000
25                       0.000000         0.000000  0.000000

medical_specialty    Endocrinology-Metabolism  Resident
admission_source_id
1                                    0.000034  0.000000
2                                    0.000000  0.000000
3                                    0.000000  0.000000
4                                    0.000000  0.000000
5                                    0.000000  0.000000
6                                    0.000000  0.000000
7                                    0.000122  0.000035
8                                    0.000000  0.000000
9                                    0.000000  0.000000
10                                   0.000000  0.000000
11                                   0.000000  0.000000
13                                   0.000000  0.000000
14                                   0.000000  0.000000
17                                   0.000000  0.000000
20                                   0.000000  0.000000
22                                   0.000000  0.000000
25                                   0.000000  0.000000

[17 rows x 73 columns]

# Outliers